#Create a new task
POST http://localhost:3333/api/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyY2ZhMjg0MmFmNjA0NmEwNDcwYjgiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkpvaG4iLCJpYXQiOjE2ODM0MTA0MzksImV4cCI6MTY4MzQxMTAzOX0.7uW-rwxIzDubHWNvnMcoLxoqVAsj3_aezAdttbH028w

{
  "title": "Клининг большого помещения",
  "description": "Провести клининг офисного помещения, сделать чисто-чисто, очень чисто, чисто-чисто, очень чисто, чисто-чисто, очень чисто",
  "deadline": "2023-05-10",
  "categoryId": 3,
  "city": "Moscow",
  "tags": [
    "Clining",
    "Home",
    "Web",
    "Program",
    "Program"
  ]
}

###

# Get task by ID
GET http://localhost:3333/api/tasks/2 HTTP/1.1

###

# Delete task by ID
DELETE http://localhost:3333/api/tasks/21 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyY2ZhMjg0MmFmNjA0NmEwNDcwYjgiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkpvaG4iLCJpYXQiOjE2ODM0MTQwMzUsImV4cCI6MTY4MzQxNDYzNX0.wVjQo0OpBOy46GGU4ohoohMzs_c5SBcphC_gpo-Mqmk

###

# Update task by ID
PATCH http://localhost:3333/api/tasks/21 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyY2ZhMjg0MmFmNjA0NmEwNDcwYjgiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkpvaG4iLCJpYXQiOjE2ODM0MTI1ODEsImV4cCI6MTY4MzQxMzE4MX0.16wRucenk7H127aw7Mb6rtNWZJvb_-6e2oFEopu-Ri8

{
  "executorId": "6452ca1f33bbee8ea383010e"
}

###

# Change task status
PATCH http://localhost:3333/api/tasks/22/status HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyY2ZhMjg0MmFmNjA0NmEwNDcwYjgiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkpvaG4iLCJpYXQiOjE2ODM0MTQwMzUsImV4cCI6MTY4MzQxNDYzNX0.wVjQo0OpBOy46GGU4ohoohMzs_c5SBcphC_gpo-Mqmk


{
  "status": "Failed"
}

###

# Put a reply
POST http://localhost:3333/api/tasks/22/reply HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyY2ZhMjg0MmFmNjA0NmEwNDcwYjgiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkpvaG4iLCJpYXQiOjE2ODM0MTQwMzUsImV4cCI6MTY4MzQxNDYzNX0.wVjQo0OpBOy46GGU4ohoohMzs_c5SBcphC_gpo-Mqmk

###

# Get all tasks and filtres
GET http://localhost:3333/api/tasks?sortDirection=desc&category=1&limit=2&page=1 HTTP/1.1

###
