#Create a new task
POST http://localhost:3333/api/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU2ZDIyN2Y3YzFiNjM2YmJmYjI2M2UiLCJlbWFpbCI6ImVsaXNAZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkVsaXMiLCJpYXQiOjE2ODM1MDY5MDcsImV4cCI6MTY4MzUwNzUwN30.LvZ63eBFs6ZWhRA5sQbzigyUHe5FCjh7LGq-NPk1gxA

{
  "title": "Разработать лендинг магазина",
  "description": "Разработать сайт, стек Next.js, Nest.js. Работа срочная, пишите телеграм в отклике. Оплата по договоренности",
  "deadline": "2023-05-11",
  "categoryId": 1,
  "city": "Vladivostok",
  "tags": [
    "Technics"
  ]
}

###

# Get task by ID
GET http://localhost:3333/api/tasks/25 HTTP/1.1

###

# Delete task by ID
DELETE http://localhost:3333/api/tasks/24 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyY2ZhMjg0MmFmNjA0NmEwNDcwYjgiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkpvaG4iLCJpYXQiOjE2ODM0MTQwMzUsImV4cCI6MTY4MzQxNDYzNX0.wVjQo0OpBOy46GGU4ohoohMzs_c5SBcphC_gpo-Mqmk

###

# Update task by ID
PATCH http://localhost:3333/api/tasks/28 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyY2ZhMjg0MmFmNjA0NmEwNDcwYjgiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkpvaG4iLCJpYXQiOjE2ODM0MTI1ODEsImV4cCI6MTY4MzQxMzE4MX0.16wRucenk7H127aw7Mb6rtNWZJvb_-6e2oFEopu-Ri8

{
  "tags": [
    "Technics"
  ]
}

###

# Change task status
PATCH http://localhost:3333/api/tasks/6/status HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU2ZDIyN2Y3YzFiNjM2YmJmYjI2M2UiLCJlbWFpbCI6ImVsaXNAZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkVsaXMiLCJpYXQiOjE2ODM1MDYyNjcsImV4cCI6MTY4MzUwNjg2N30.asjUGF0oOfH8ZsP63L5MAwCXLsyToQLp6ktdfdyEXKA


{
  "status": "InProgress",
  "executorId": "6457ccd22d75f5c87f8b7657"
}

###

# Put a reply
POST http://localhost:3333/api/tasks/6/reply HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU3Y2NkMjJkNzVmNWM4N2Y4Yjc2NTciLCJlbWFpbCI6ImFsaWNlQGdtYWlsLmNvbSIsInJvbGUiOiJFeGVjdXRvciIsIm5hbWUiOiJBbGljZSIsImlhdCI6MTY4MzUwNjIyNiwiZXhwIjoxNjgzNTA2ODI2fQ.pg-m7U_T_JcOg5IqIb-Be0ScQM7n6jRVlS7BRPcXTt8

###

# Get all tasks and filtres
GET http://localhost:3333/api/tasks?sortDirection=desc&sortType=repliesAmount&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU3Y2NkMjJkNzVmNWM4N2Y4Yjc2NTciLCJlbWFpbCI6ImFsaWNlQGdtYWlsLmNvbSIsInJvbGUiOiJFeGVjdXRvciIsIm5hbWUiOiJBbGljZSIsImlhdCI6MTY4MzQ5MDkxOSwiZXhwIjoxNjgzNDkxNTE5fQ.-hRlUzjUFre-myewt0u3E-4gnGi397ZDy_swddHrrJw

###

# Get my tasks and filtres
GET http://localhost:3333/api/tasks/mytasks?status=new HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU2ZDIyN2Y3YzFiNjM2YmJmYjI2M2UiLCJlbWFpbCI6ImVsaXNAZ21haWwuY29tIiwicm9sZSI6IkN1c3RvbWVyIiwibmFtZSI6IkVsaXMiLCJpYXQiOjE2ODM1MDY5MDcsImV4cCI6MTY4MzUwNzUwN30.LvZ63eBFs6ZWhRA5sQbzigyUHe5FCjh7LGq-NPk1gxA
###

