# Create a new user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Alice",
  "email": "alice@gmail.com",
  "city": "Москва",
  "password": "123456",
  "role": "Исполнитель",
  "dateBirth": "1990-02-22"
}

###

# Get user by ID
GET http://localhost:3333/api/auth/f4e8d221-1b79-4bc8-863d-a3d3079b8919 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "alice@gmail.com",
  "password": "123456"
}

###
