# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "email": "john@gmail.com",
  "city": "Moscow",
  "password": "123456",
  "role": "Исполнитель",
  "dateBirth": "1990-02-22"
}

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/642eb5c4859b4c3ee7ea7b50 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDJlYjVjNDg1OWI0YzNlZTdlYTdiNTAiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6ItCY0YHQv9C-0LvQvdC40YLQtdC70YwiLCJuYW1lIjoiTWFyeSIsImlhdCI6MTY4MjAyMDk4MSwiZXhwIjoxNjgyMDIxNTgxfQ.uvLBKwWeA_XrYKATehxSWmFTX7MMn3wWzK7UfQQk9pU

###

# Update user by ID
PATCH http://localhost:3000/api/auth/642eb5c4859b4c3ee7ea7b50 HTTP/1.1
Content-Type: application/json

{
  "name": "Mary",
  "city": "Владивосток",
  "info": "Супер классный специалист!",
  "speciality": [
    "HTML",
    "CSS"
  ]
}

###

# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDRhYmUxNThiZjQzNWQxOWZiOWFmYmUiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwicm9sZSI6ItCY0YHQv9C-0LvQvdC40YLQtdC70YwiLCJuYW1lIjoiSm9obiIsImlhdCI6MTY4Mjk3MzU2OSwiZXhwIjoxNjg1NTY1NTY5fQ.dVPqXYxegj1k1VYcez45OZ07VTBwCs3dW6FeLG7rQpM
