# Create a new response
POST http://localhost:3333/api/responses HTTP/1.1
Content-Type: application/json

{
  "message": "Задание выполнено качественно и в срок",
  "taskId": "24",
  "estimation": 5
}

###
